[profile.default]
src = 'contracts'
out = 'forge/out'
cache_path = 'forge/cache'
libs = ['node_modules', 'lib']
test = 'test/foundry'
# compilers config
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 10000
build_info = true
extra_output = ["storageLayout"]
